config/routes.rb
require 'sidekiq/web'

class RootRouter
  def initialize
    @root = "sso"
  end

  def matches?(request)
    request.subdomain == @root
  end
end

class TenantRouter
  def initialize
    @domains = Account.pluck(:subdomain)
  end

  def matches?(request)
    @domains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  constraints RootRouter.new do
    scope module: 'sso' do
      mount Sidekiq::Web, at: '/sidekiq'
      get '/', to: 'welcome#index'
    end
  end

  constraints TenantRouter.new do
    devise_for :sso_users, controllers: {
      sessions: 'sso_users/sessions'
    }
    scope module: 'tenant' do
      get '/', to: 'welcome#index'
      resources :organizations
      get '/application', to: "apps#index"
    end
  end
end

app/models/tenants.rb
module Tenants
  def self.table_name_prefix
    "tenants_"
  end
end

app/models/tenants/application.rb
class Tenants::Application < ApplicationRecord
  has_many :user_applications
  has_many :sso_users, through: :user_applications
end

app/models/tenants/organization.rb
class Tenants::Organization < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :title, presence: true
  validates :follback_page_url, presence: true

  has_and_belongs_to_many :users, class_name: 'Tenants::Organization', join_table: :tenants_user_organizations
end

app/models/tenants/user_application.rb
class Tenants::UserApplication < ApplicationRecord
  belongs_to :sso_user
  belongs_to :application
end

app/controllers/tenant/application_controller.rb
module Tenant
  class ApplicationController < ::ApplicationController
    # before_action :authenticate_sso_user!


    def strong_params
      # Skipping additional settings just beacouse additional settings contains 
      # The class name and path and we don't want this here
      @attributes.except(:additional)
    end

    def permit_params
      params.require(@attributes[:additional][:klass].to_s.underscore).permit(*strong_params.keys)
    end
  end
end

app/controllers/tenant/apps_controller.rb
class Tenant::AppsController < Tenant::ApplicationController
  def index
    @apps =  Tenants::Application.all
  end
end

app/controllers/tenant/organizations_controller.rb
class Tenant::OrganizationsController < Tenant::ApplicationController
  before_action :set_attributes

  def index
    @orgs = Tenants::Organization.all.order(created_at: :desc)
  end

  def create
    @org = Tenants::Organization.new(permite_org_params)

    unless @org.save
      render :index
    end
  end

  def set_attributes
    @create_org_hash = {
      "name": :string,
      "title": :string,
      "follback_page_url": :text,
      "additional": {
        "klass": Tenants::Organization,
        "path": organizations_path
      }
    }
  end


  private
  def permite_org_params
    params.require(:tenants_organization).permit(*@create_org_hash.except(:additional).keys)
  end
end

app/controllers/tenant/users_controller.rb
class Tenant::UsersController < Tenant::ApplicationController
  before_action :set_attributes

  def index
  end

  def create
  end

  def new
  end



  private
  def set_attributes
    @attributes = {
      "email": :string,
      "password": :password,
      "password_confirmation": :password,
      "additional": {
        "klass": SsoUser,
        "path": users_path
      }
    }
  end
end

app/controllers/tenant/welcome_controller.rb
class Tenant::WelcomeController < Tenant::ApplicationController
  # before_action :authenticate_sso_user!
  layout 'admin'

  def index
  end
end

app/helpers/tenant/apps_helper.rb
module Tenant::AppsHelper
end

app/helpers/tenant/organizations_helper.rb
module Tenant::OrganizationsHelper
end

app/helpers/tenant/users_helper.rb
module Tenant::UsersHelper
end

app/helpers/tenant/welcome_helper.rb
module Tenant::WelcomeHelper
end

app/views/tenant/users/index.html.erb
<section class="py-12 py-lg-24 bg-black position-relative overflow-hidden">
  <div class="container py-2">
    <div class="mw-5xl mx-auto mb-20 text-center">
      <h2 class="font-heading p-2">Users</h2>
    </div>
    <div class="text-center mb-4">
      <%= link_to "New User", new_user_path, type: "button", class: "btn btn-primary", data: { turbo_frame: "model-popup", turbo_cache: false }%>
    </div>
    <div class="">
      <table class="table table-dark table-borderless">
        <thead class="p-2">
          <tr>
            <th class="my-2 bg-transparent border-bottom border-dark" scope="col">
              <div class="pb-1">
                <span class="fw-medium fs-9 text-secondary-light">User Full name</span>
              </div>
            </th>
            <th class="my-2 bg-transparent border-bottom border-dark" scope="col">
              <div class="pb-1">
                <span class="fw-medium fs-9 text-secondary-light">Organization</span>
              </div>
            </th>
            <th class="my-2 bg-transparent border-bottom border-dark" scope="col">
              <div class="pb-1">
                <span class="fw-medium fs-9 text-secondary-light">Roles</span>
              </div>
            </th>
            <th class="my-2 bg-transparent border-bottom border-dark" scope="col">
              <div class="pb-1">
                <span class="fw-medium fs-9 text-secondary-light">Rights</span>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th class="p-0 bg-transparent border-bottom border-dark" scope="row">
              <div class="px-6 py-6">
                <span class="fs-5 fw-normal">Product Manager, Instagram Camera</span>
              </div>
            </th>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-5"><a class="btn btn-sm py-2 lh-sm btn-outline-primary" href="#">Marketing</a></div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Full Time</span>
              </div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Full Time</span>
              </div>
            </td>
          </tr>
          <tr>
            <th class="p-0 bg-transparent border-bottom border-dark" scope="row">
              <div class="px-6 py-6">
                <span class="fs-5 fw-normal">Research Director</span>
              </div>
            </th>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-5"><a class="btn btn-sm py-2 lh-sm btn-outline-primary" href="#">Customer Success</a></div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Full Time</span>
              </div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Miami</span>
              </div>
            </td>
          </tr>
          <tr>
            <th class="p-0 bg-transparent border-bottom border-dark" scope="row">
              <div class="px-6 py-6">
                <span class="fs-5 fw-normal">Customer Success Manager</span>
              </div>
            </th>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-5"><a class="btn btn-sm py-2 lh-sm btn-outline-primary" href="#">Marketing</a></div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Full Time</span>
              </div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">San Francisco</span>
              </div>
            </td>
          </tr>
          <tr>
            <th class="p-0 bg-transparent border-bottom border-dark" scope="row">
              <div class="px-6 py-6">
                <span class="fs-5 fw-normal">Engineering Manager</span>
              </div>
            </th>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-5"><a class="btn btn-sm py-2 lh-sm btn-outline-primary" href="#">Software Engineering</a></div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Freelance</span>
              </div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Boston</span>
              </div>
            </td>
          </tr>
          <tr>
            <th class="p-0 bg-transparent border-bottom border-dark" scope="row">
              <div class="px-6 py-6">
                <span class="fs-5 fw-normal">Product Designer</span>
              </div>
            </th>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-5"><a class="btn btn-sm py-2 lh-sm btn-outline-primary" href="#">Design</a></div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Full Time</span>
              </div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Los Angeles</span>
              </div>
            </td>
          </tr>
          <tr>
            <th class="p-0 bg-transparent border-bottom border-dark" scope="row">
              <div class="px-6 py-6">
                <span class="fs-5 fw-normal">Product Manager, Instagram Camera</span>
              </div>
            </th>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-5"><a class="btn btn-sm py-2 lh-sm btn-outline-primary" href="#">Design</a></div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Full Time</span>
              </div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">San Antonio</span>
              </div>
            </td>
          </tr>
          <tr>
            <th class="p-0 bg-transparent border-bottom border-dark" scope="row">
              <div class="px-6 py-6">
                <span class="fs-5 fw-normal">Product Manager, Instagram Camera</span>
              </div>
            </th>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-5"><a class="btn btn-sm py-2 lh-sm btn-outline-primary" href="#">Design</a></div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Full Time</span>
              </div>
            </td>
            <td class="p-0 bg-transparent border-bottom border-dark">
              <div class="px-6 py-6">
                <span class="d-inline-block fw-normal">Los Angeles</span>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="text-center"><a class="btn btn-primary w-100 mw-xs fw-medium" href="#">See all positions</a></div>
  </div>
</section>

app/views/tenant/users/new.html.erb
<%= turbo_frame_tag "model-popup" do %>
  <div class="text-center mb-4 d-none" data-controller="tenants--popup-cliker">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#user" id="model-pop">
    </button>
  </div>
  <%= render 'tenant/modals/basic_modal', model_id: "user", heading: "New User", builder: @attributes, submit_btn_text: "Create User" %>
<%end%>